### ISSUE TITLE
Some edits required for ``gibbs_simulation.R``

### ISSUE THREAD

**Issue by EoghanONeill** [adam-iqbal/selection-spike-slab#2]
The following edits are required for ``gibbs_simulation.R`` to run:

``p_param=p_param`` must be added as an argument to the function ``gibbs_parallel``.

``parallel_seed_testing_6'`` must be replaced by a call to ``gibbs_parallel``.

The line ``var_scaling <- FALSE`` must be added before the call to  ``gibbs_parallel``.

EDIT: ``p_param`` should be replaced by ``rho_param``, and ``init_p`` should be replaced by ``init_rho`` because these are the names of the inputs to ``gibbs_spike_slab``.

**Comment by adam-iqbal** [comment]
Thanks for pointing these out. I've done all of these (added var_scaling=FALSE, and changed the variable names in the input) to the code. Also added a comment about the folder (the way it's written, there needs to be a sub-folder called "out" of whatever directory you supply) and another bug (the code called beep() at the end which relied on beepr - since it was at the end it didn't matter but it's probably better to not have an error).

Please let me know if it still doesn't run.

**Comment by EoghanONeill** [comment]
The following error occurs:
```Error in { : task 1 failed - "cannot open the connection"
In addition: Warning message:
In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): alpha_slab, alpha_spike, beta_slab, beta_spike, burn_in, corr, folder_path, n_samp, p, rho_param, start_seed, tau_0_alpha, tau_0_beta, tau_1_alpha, tau_1_beta, true_alpha, true_beta, var_scaling```

This might be because I am using a Windows computer. I will write a different parallelized function with parLapply.

**Comment by EoghanONeill** [comment]
Actually the script runs successfully if I remove the following lines:
```
filename = paste(folder_path,"/out/out",start_seed+i-1,".rds",sep='')
saveRDS(test_gibbs,file=filename)
```
and if I replace ``return(NA)`` with ``return(test_gibbs)``.

The output is a list of length ``num_seeds*5`` because 5 objects are included in the output of ``gibbs_spike_slab()``.


The following warning message still occurs:
```
Warning message:
In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): alpha_slab, alpha_spike, beta_slab, beta_spike, burn_in, corr, n_samp, p, rho_param, start_seed, tau_0_alpha, tau_0_beta, tau_1_alpha, tau_1_beta, true_alpha, true_beta, var_scaling
```

**Comment by adam-iqbal** [comment]
So for the first of these: the way I ran the simulation was to store the entire output in .Rds files, so I would not have to re-run the simulations every time I wanted to analyse the results. So there's no output to the parallel function itself in the code - the main use is the side effect of writing each simulation to a file.
Except the way I coded it up was that if you supply directory "X" to folder_name, it writes seed k to "X/out/outk.Rds", so it'll return an error if "X" doesn't have a subfolder "out". I've updated the code so this isn't necessary.
If you don't need to write the output to file and want some direct output, the changes you made are fine.

The second is an issue I had with parallel coding specifically the lines
```
  oper <- foreach(i=1:num_seeds, .combine='comb', .init=c(),
                  .export = ls(globalenv())) %dopar% {
```
I couldn't figure out how to make sure the inner loop used all the variables and functions without manually writing each one (of which there were many) as a list for the .export argument. My workaround at the time was to use `.export = ls(globalenv())) `, which imports all the variables in the global environment. I don't think this is good practice, but it worked at the time.
The warning comes from some of the variables being imported from the global environment being in the local environment already. But all of those should be the same in both environments so there shouldn't be any conflict.

**Comment by EoghanONeill** [comment]
Thank you for explaining. I save the output in a non-parallelized for-loop after the parallelized code to avoid the error.

Thank you also for providing this simulation code. It has been very useful for comparing other new methods to your method.
